name: Build and Start Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: bun install

    - name: Build
      run: bun run build

    - name: Start
      run: bun start
